name: presto-brightree-service

on:
  workflow_dispatch:
    inputs:
      build_env_name:
        description: 'Build Environment Name'
        required: true
        type: string
env:
  AWS_DEFAULT_REGION : us-east-1
  ECR_REPOSITORY : presto_brightree_service

jobs:
  
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install maven dependencies
      run: |  
          mvn -DskipTests -Dspring.profiles.active=dev clean install
          mvn -DskipTests -Dspring.profiles.active=dev package

    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: $GITHUB_SHA
      run: |
        docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG  

    - name: ecs deploy action
      env:
        CLUSTER_NAME: presto_cluster-${{ inputs.build_env_name }}
        TASKDEF_NAME: brightree-service-${{ inputs.build_env_name }}
        SERVICE_NAME: brightree-service-${{ inputs.build_env_name }}
      run: |
        sudo apt-get install jq -y
        jq --version
        aws ecs describe-task-definition --task-definition $TASKDEF_NAME > task-def.json
        jq .taskDefinition task-def.json > taskdefinition.json
        jq 'del(.taskDefinitionArn)' taskdefinition.json | jq 'del(.revision)' | jq 'del(.status)' | jq 'del(.requiresAttributes)' | jq 'del(.compatibilities)' | jq 'del(.registeredAt)'| jq 'del(.registeredBy)' > container-definition.json
        aws ecs register-task-definition --cli-input-json file://container-definition.json  
        aws ecs update-service --cluster  $CLUSTER_NAME --service  $SERVICE_NAME --task-definition  $TASKDEF_NAME      
      

